### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by sweetiepiggy** [sweetiepiggy/Bus-When-Twin-Cities#3]
It would be nice if someone who speaks Spanish could compare [values-es/strings.xml](../blob/next/app/src/main/res/values-es/strings.xml) to [values/strings.xml](../blob/next/app/src/main/res/values/strings.xml) and check/improve the translation.

If it helps to put it in context, there are a few screenshots at
https://play.google.com/store/apps/details?id=com.sweetiepiggy.buswhentwincities&hl=es

**Comment by agudelotmateo** [comment]
Hi,

I don't know much about the project but at least I think I can help with this task.

I spotted some words misspelled (like "Licensia") and some inconsistencies. Others seem to be just made decisions about the way to communicate the message so I won't touch those.

**Comment by sweetiepiggy** [comment]
Hi,

That sounds great, whatever you're willing to do would be awesome.

We've gotten a few Spanish users of this app but they tend to uninstall at a higher rate than others, so hopefully this will help to improve the experience for them.

(Feel free to add your name to the copyright message of any files you touch, if you'd like.)
